---
title: Het waarnemen van kleine bewegingen
hero_image: images/banner.png
description: Gevoeligere bewegingen gebruiken om acties te activeren
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Inleiding
