title: micro:bit fine movements
hero_image: images/banner.png
description: Using more sensitive movements to trigger actions
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Introduction
